export const INITIAL_FEATURE_STATE = {
  WorldSpeed: false,
  WorldSpeedValue: 1,
  GodMode: false,
  InfiniteStamina: false,
  AutoHeal: false,
  OneHitKill: false,
  KillAura: false,
  AutoLoot: false,
  MultiplyDamage: false,
  AutoLootTreasure: false,
  MultiDamageValue: 0,
  ENHANCE: false,
  DAMAGE_UP: false,
  DEFENSE_UP: false,
  INVINCIBLE: false,
  DUMB_ENEMIES: false,
  BLOCK_SHIELD: false,
  IMMUNE_CONTROL: false,
  RESURRECT_VIP: false,
  SUPER_VIP2: false,
} as const;
